---
- hosts: al2
  become: yes
  tasks:
    - name: Install nano
      package: 
        name: nano
        state: present
    - name: Install git
      package:
        name: git
        state: present
    - name: Install gcc
      package:
        name: gcc
        state: present
    - name: Install tree
      package:
        name: tree
        state: present    
    - name: Install python3
      package:
        name: python3
        state: present
    - name: Install postgresql
      package:
        name: postgresql
        state: present
    - name: Install python3-devel
      package:
        name: python3-devel
        state: present 
    - name: Install postgresql-devel
      package:
        name: postgresql-devel
        state: present    