---
plugin: aws_ec2
region:
  - us-west-1
keyed_groups:
  # add hosts to tag_Name_value groups for each aws_ec2 host's tags.Name variable
  - key: tags.Name
    prefix: tag_Name_
    separator: ""
  - key: tags.Module
    prefix: tag_Module_
    separator: ""
# all:
#   hosts:
#     ec2-18-221-129-201.us-east-2.compute.amazonaws.com:
#     ec2-18-191-207-42.us-east-2.compute.amazonaws.com:
#   children:
#     al2:
#       hosts:
#         ec2-18-221-129-201.us-east-2.compute.amazonaws.com:
#         ec2-18-191-207-42.us-east-2.compute.amazonaws.com:
#       vars:
#         ansible_user: ec2-user
#         ansible_python_interpreter: /usr/bin/python